### ISSUE TITLE
error: could not lock config file /github/home/.gitconfig: Permission denied

### ISSUE THREAD

**Issue by krishnadasika** [digi-wolk/olaudit-action#5]
I keep getting the below error when the action runs
error: could not lock config file /github/home/.gitconfig: Permission denied

Does this action gives report for Nuget package manager?

**Comment by tvaughanRR** [comment]
I also got that problem.  I've tried a bunch of configuration to try to get around it, but can't seem to solve this.  Here's my config, in case tis helps:

```
name: Audit licenses

on:
  pull_request:
    branches: [main, master]

jobs:
  audit-licenses:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.OPENSOURCE_LICENSE_CHECKING_GHA_PAT }}
    steps:
      - uses: actions/checkout@v4

      - name: setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --add safe.directory "$(pwd)"
        shell: bash

      - name: OSS License Auditor
        uses: digi-wolk/olaudit-action@v1
        with:
          path: .
          comment-on-pr: true
          github-token: ${{ secrets.OPENSOURCE_LICENSE_CHECKING_GHA_PAT }}
```

And the error:

<img width="1410" height="351" alt="Image" src="https://github.com/user-attachments/assets/b00fd1be-2349-48bd-9b46-c738d24e7e5d" />
